fix for usersetup.py to check, if gid and uid are not in use
crops/extsdk-container pull request #7
Opened 2019-05-15 11:03 UTC by jirivrany

Existing version of usersetup.py crashes, if the gid or uid are already in use in the container. For example if the container is started with usersetup.py, then exited and then started again.

2019-05-22 17:25 UTC, rewitt1 commented
Hi @jirivrany,

Could you provide a more specific example for the workflow where this breaks? i.e. the commands you ran to create the container and subsequently run it again.

I want to make sure to understand your workflow since these images were to created with the idea of always being run stateless.

2019-05-28 15:56 UTC, jirivrany commented
Hi @rewitt1 
yes you are right, we are using the container differently. In fact we are using https://github.com/crops/poky-container container, but it is downolading some files from this container. 

Our workflow is as follows.  For the debugging / development process of some Yocto images we need to use the container more like an isolated workspace. We are starting it again after the first run. This is because some parts of our build script are working, and some later parts not.  And therefore we don't want to rerun the working parts again because they are time-consuming. 

So I thought, that if someone will use the container as we did, he or she may run to the some issue as we did.

2019-06-25 19:30 UTC, rewitt1 requested changes
Hi @jirivrany,

Sorry I took so long to respond again, I've had no time it seems.

I was wondering if we should hide this behavior behind an argument, so it must be explicitly requested? The reason I think this might be beneficial is for the cases that the user already exists due to the distro being used. We automatically then grant file permissions for a bunch of files to a user where they might be hoping that they can't modify any files they shouldn't.

I could probably be swayed either way, its just a question I had.

Outside of that, could you change the commit message to be a bit more descriptive following guidelines like https://commit.style/ and add your "Signed-off by" line? Something like:
```
usersetup.py: Don't try to create existing users or groups

Reasons why here...
```

Thanks!

2019-09-03 16:18 UTC, btgoodwin commented
Any updates on this?  I patched this out of the crops/poky container by modifying the two shell scripts (owned here) to make the final `else` be `elif [ ! $(getent passwd pokyuser) ]; then` (for checking if the user already exists) and `elif [ ! $(getent group pokuser) ]; then` (respectively for groups).  If you would like I can fork and submit a PR for this, but it's basically equivalent behavior.

2019-09-12 08:03 UTC, jirivrany commented
@rewitt1 Hi, I almost forgot your suggestion for changes during the summer. The commit message should be according to the guidelines now. Thanks to @btgoodwin for waking me up ;-)

I'm not sure if hiding the behavior behind the argument will help. Only in that case, that the crash of the container is desired behavior as protection against unwanted rerun?

2019-09-12 11:18 UTC, btgoodwin commented
@jirivrany See #9 for a thread on what we were thinking about.

My use case is in GitLab CI with the downstream crops/poky container where each stage runs in a container, and each step of a stage's script re-enters the container (by nature of how the gitlab runner is designed) so we end up getting nuisance errors.

2019-09-24 19:24 UTC, rewitt1 requested changes
Hi @jirivrany,

Thanks for updating the commit message, and I was about to merge this, but there are still a couple of things that need to be fixed.

The paragraph lines should not be any longer than 72 characters, or worst case 80. This helps make sure its easily legible and not truncated by tooling.

Also your signed off by should look like
```
Signed-off-by: Jiri Vrany <jiri.vrany@gmail.com>
```
git will add the "Signed-off-by:" for you if you add "-s" to "git commit".

Thanks for this, I just tested it out and it seems to work great.

2019-09-25 08:38 UTC, jirivrany commented
@rewitt1 thank you. I changed the line length now it should be fine.

2019-09-25 16:31 UTC, rewitt1 commented
Hi @jirivrany,

I see you changed the line length in usersetup.py, but I was actually referring to the commit message. I was trying to imply that but mentioning the signed off by line, but could have been clearer.

If you change the commit message line length for https://github.com/crops/extsdk-container/pull/7/commits/cf4603553200bfd54afa7ae6ed2545aabf3b9b4a and fix the signed off, it would be fine.

Make sure to only have one commit on the branch as well, because now there are two. Sorry for not being clearer.

2019-09-25 17:12 UTC, jirivrany commented
Hi @rewitt1 
my mistake. I should ask what lines before editing the wrong file. Now it should be fixed.

2019-09-25 17:56 UTC, merged